# Generated by Django 6.1 on 2026-08-14 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(verbose_name='Дата гри')),
                ('start_time', models.TimeField(verbose_name='Час початку')),
                ('end_time', models.TimeField(verbose_name='Час завершення')),
                ('players_count', models.PositiveIntegerField(default=1, verbose_name='Кількість гравців')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Загальна вартість (грн)')),
                ('status', models.CharField(choices=[('new', 'Очікує оплати'), ('paid', 'Оплачено'), ('cancelled', 'Скасовано'), ('completed', 'Завершено')], default='new', max_length=20, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Коментар до замовлення')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('arena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='catalog.arena', verbose_name='Арена')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Бронювання',
                'verbose_name_plural': 'Бронювання',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сума оплати')),
                ('status', models.CharField(default='success', max_length=20, verbose_name='Статус')),
                ('transaction_id', models.CharField(blank=True, max_length=100, verbose_name='ID транзакції')),
                ('paid_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата й час оплати')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='booking.booking', verbose_name='Бронювання')),
            ],
            options={
                'verbose_name': 'Оплата',
                'verbose_name_plural': 'Оплати',
            },
        ),
    ]
