# Generated by Django 6.1 on 2026-08-14 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(verbose_name='Рахунок / Очки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата гри')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_scores', to=settings.AUTH_USER_MODEL, verbose_name='Гравець')),
            ],
            options={
                'verbose_name': 'Результат гри',
                'verbose_name_plural': 'Результати ігор',
                'ordering': ['-score'],
            },
        ),
    ]
