# Generated by Django 6.1 on 2026-08-14 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва категорії')),
                ('slug', models.SlugField(unique=True, verbose_name='URL-слаг')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
            },
        ),
        migrations.CreateModel(
            name='Arena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва арени/майданчика')),
                ('description', models.TextField(verbose_name='Опис')),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Ціна за годину (грн)')),
                ('photo', models.ImageField(upload_to='arenas/', verbose_name='Головне фото')),
                ('max_players', models.PositiveIntegerField(default=10, verbose_name='Макс. кількість гравців')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступно для бронювання')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arenas', to='catalog.category', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Арена',
                'verbose_name_plural': 'Арени',
            },
        ),
    ]
