# Generated by Django 6.1 on 2026-08-18 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arena',
            options={},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.RemoveField(
            model_name='arena',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='arena',
            name='photo',
        ),
        migrations.AddField(
            model_name='arena',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='arenas/'),
        ),
        migrations.AlterField(
            model_name='arena',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arenas', to='catalog.category'),
        ),
        migrations.AlterField(
            model_name='arena',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='arena',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='arena',
            name='max_players',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='arena',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='arena',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
